name = "ZMQPoller"
uuid = "4b32e1d1-572c-43b1-a481-e7eed928be34"
authors = ["Cas Bex <cas.bex@kuleuven.be>"]
version = "0.2.0"

[deps]
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
ZMQ = "1.4"
Aqua = "0.8.7"
Test = "1"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
